data:
  raw_path: data/raw
  splits: ["train", "test"]
  processed_path: data/processed
  sample_rate: 16000
  n_fft: 1024
  hop_length: 512
  n_mels: 80
  segment_length: 256
model:
  checkpoint_dir: models/checkpoints
training:
  epochs: 50
  batch_size: 16
  lr: 1e-4